package(default_testonly = 1)

py_library(
    name = "broken_mypy_typings",
    srcs = ["broken_mypy_typings.py"],
    srcs_version = "PY3",
)

py_library(
    name = "correct_mypy_typings",
    srcs = ["correct_mypy_typings.py"],
    srcs_version = "PY3",
)