py_binary(
    name = "prime_number_seive",
    srcs = ["prime_number_seive.py"],
    main = "prime_number_seive.py",
    python_version = "PY3",
)

py_binary(
    name = "simple_class",
    srcs = ["simple_class.py"],
    main = "simple_class.py",
    python_version = "PY3",
)

py_binary(
    name = "word_freqs_with_dict",
    srcs = ["word_freqs_with_dict.py"],
    main = "word_freqs_with_dict.py",
    python_version = "PY3",
    deps = []
)

