workspace(name = "examples")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

########################
# MYPY SUPPORT
########################

local_repository(
    name = "mypy_integration",
    path = "../",
)

load("@mypy_integration//repositories:repositories.bzl", mypy_integration_repositories = "repositories")

mypy_integration_repositories()

load("@mypy_integration//:config.bzl", "mypy_configuration")

mypy_configuration("//tools/typing:mypy.ini")

########################
# PYTHON SUPPORT
########################
rules_python_version = "5c948dcfd4ca79c2ed3a87636c46abba9f5836e9"

http_archive(
    name = "rules_python",
    sha256 = "76e817a5e540f4c8a8b5e1de1e7afee6dfa42d78112a3694244450287ac20ebb",
    strip_prefix = "rules_python-{version}".format(version = rules_python_version),
    url = "https://github.com/bazelbuild/rules_python/archive/{version}.tar.gz".format(version = rules_python_version),
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

python_register_toolchains(
    name = "python3_8",
    python_version = "3.8",
)

load("@python3_8//:defs.bzl", python_interpreter = "interpreter")
load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "my_deps",
    python_interpreter_target = python_interpreter,
    requirements_lock = "//third_party:requirements.txt",
)

load("@my_deps//:requirements.bzl", install_my_deps = "install_deps")

install_my_deps()

pip_parse(
    name = "my_mypy_deps",
    python_interpreter_target = python_interpreter,
    requirements_lock = "//tools/typing:mypy_requirements.txt",
)

load("@my_mypy_deps//:requirements.bzl", install_my_pypy_deps = "install_deps")

install_my_pypy_deps()

########################
# OTHER
########################

http_archive(
    name = "bazel_skylib",
    sha256 = "cd55a062e763b9349921f0f5db8c3933288dc8ba4f76dd9416aac68acee3cb94",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.5.0/bazel-skylib-1.5.0.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.5.0/bazel-skylib-1.5.0.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()
