workspace(name = "examples")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

########################
# MYPY SUPPORT
########################

local_repository(
    name = "mypy_integration",
    path = "../",
)

load("@mypy_integration//repositories:repositories.bzl", mypy_integration_repositories = "repositories")

mypy_integration_repositories()

########################
# PYTHON SUPPORT
########################
rules_python_version = "0.27.1"

http_archive(
    name = "rules_python",
    sha256 = "e85ae30de33625a63eca7fc40a94fea845e641888e52f32b6beea91e8b1b2793",
    strip_prefix = "rules_python-{version}".format(version = rules_python_version),
    url = "https://github.com/bazelbuild/rules_python/archive/{version}.tar.gz".format(version = rules_python_version),
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

python_register_toolchains(
    name = "python3_8",
    python_version = "3.8",
)

load("@python3_8//:defs.bzl", python_interpreter = "interpreter")
load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "my_deps",
    python_interpreter_target = python_interpreter,
    requirements_lock = "//third_party:requirements.txt",
)

load("@my_deps//:requirements.bzl", install_my_deps = "install_deps")

install_my_deps()

pip_parse(
    name = "my_mypy_deps",
    python_interpreter_target = python_interpreter,
    requirements_lock = "//tools/typing:mypy_requirements.txt",
)

load("@my_mypy_deps//:requirements.bzl", install_my_pypy_deps = "install_deps")

install_my_pypy_deps()

########################
# OTHER
########################

http_archive(
    name = "bazel_skylib",
    sha256 = "9f38886a40548c6e96c106b752f242130ee11aaa068a56ba7e56f4511f33e4f2",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.6.1/bazel-skylib-1.6.1.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.6.1/bazel-skylib-1.6.1.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()
