name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: [".", "examples"]
    defaults:
      run:
        working-directory: ${{ matrix.folder }}

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v4
      - uses: p0deje/setup-bazel@0.9.0
        with:
          bazelrc: common --announce_rc --color=yes
      - name: Run tests
        run: bazel test //...

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run integration tests
        run: ./test.sh
