load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "types",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
    visibility = ["//test:__subpackages__"],
    deps = [],
)
